FORMAT: 1A
HOST: https://1forge.com/forex-quotes

# 1Forge Finance APIs
Stock and Forex Data and Realtime Quotes

# Group forex

## Quotes [/quotes]

### Get quotes for all symbols [GET]
Get quotes

+ Response 200 

        A list of quotes





## Symbols [/symbols]

### Get a list of symbols for which we provide realtime quotes [GET]
Symbol List

+ Response 200 (application/json)

        A list of symbols

    + Attributes (array[string])



