{
  "openapi": "3.0.0",
  "info": {
    "title": "Spotify Web API with fixes and improvements from sonallux",
    "description": "You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.\n\nIn order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0[...]",
    "contact": {
      "name": "sonallux",
      "url": "https://github.com/sonallux/spotify-web-api"
    },
    "version": "2024.3.3"
  },
  "servers": [
    {
      "url": "https://api.spotify.com/v1",
      "variables": {}
    },
    {
      "url": "https://accounts.spotify.com",
      "variables": {}
    }
  ],
  "paths": {
    "/albums/{id}": {
      "get": {
        "tags": [
          "Albums"
        ],
        "summary": "get-an-album",
        "description": "Get Spotify catalog information for a single album.\n",
        "operationId": "get-an-album",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/albums": {
      "get": {
        "tags": [
          "Albums"
        ],
        "summary": "get-multiple-albums",
        "description": "Get Spotify catalog information for multiple albums identified by their Spotify IDs.\n",
        "operationId": "get-multiple-albums",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/albums/{id}/tracks": {
      "get": {
        "tags": [
          "Albums",
          "Tracks"
        ],
        "summary": "get-an-albums-tracks",
        "description": "Get Spotify catalog information about an album’s tracks.\nOptional parameters can be used to limit the number of tracks returned.\n",
        "operationId": "get-an-albums-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/me/albums": {
      "get": {
        "tags": [
          "Albums",
          "Library"
        ],
        "summary": "get-users-saved-albums",
        "description": "Get a list of the albums saved in the current Spotify user's 'Your Music' library.\n",
        "operationId": "get-users-saved-albums",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Albums",
          "Library"
        ],
        "summary": "save-albums-user",
        "description": "Save one or more albums to the current user's 'Your Music' library.\n",
        "operationId": "save-albums-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Albums",
          "Library"
        ],
        "summary": "remove-albums-user",
        "description": "Remove one or more albums from the current user's 'Your Music' library.\n",
        "operationId": "remove-albums-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      }
    },
    "/me/albums/contains": {
      "get": {
        "tags": [
          "Albums",
          "Library"
        ],
        "summary": "check-users-saved-albums",
        "description": "Check if one or more albums is already saved in the current Spotify user's 'Your Music' library.\n",
        "operationId": "check-users-saved-albums",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      }
    },
    "/browse/new-releases": {
      "get": {
        "tags": [
          "Albums"
        ],
        "summary": "get-new-releases",
        "description": "Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player’s “Browse” tab).\n",
        "operationId": "get-new-releases",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/artists/{id}": {
      "get": {
        "tags": [
          "Artists"
        ],
        "summary": "get-an-artist",
        "description": "Get Spotify catalog information for a single artist identified by their unique Spotify ID.\n",
        "operationId": "get-an-artist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/artists": {
      "get": {
        "tags": [
          "Artists"
        ],
        "summary": "get-multiple-artists",
        "description": "Get Spotify catalog information for several artists based on their Spotify IDs.\n",
        "operationId": "get-multiple-artists",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/artists/{id}/albums": {
      "get": {
        "tags": [
          "Artists",
          "Albums"
        ],
        "summary": "get-an-artists-albums",
        "description": "Get Spotify catalog information about an artist's albums.\n",
        "operationId": "get-an-artists-albums",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/artists/{id}/top-tracks": {
      "get": {
        "tags": [
          "Artists",
          "Tracks"
        ],
        "summary": "get-an-artists-top-tracks",
        "description": "Get Spotify catalog information about an artist's top tracks by country.\n",
        "operationId": "get-an-artists-top-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/artists/{id}/related-artists": {
      "get": {
        "tags": [
          "Artists"
        ],
        "summary": "get-an-artists-related-artists",
        "description": "Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community's listening history.\n",
        "operationId": "get-an-artists-related-artists",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/audiobooks/{id}": {
      "get": {
        "tags": [
          "Audiobooks"
        ],
        "summary": "get-an-audiobook",
        "description": "Get Spotify catalog information for a single audiobook. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
        "operationId": "get-an-audiobook",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/audiobooks": {
      "get": {
        "tags": [
          "Audiobooks"
        ],
        "summary": "get-multiple-audiobooks",
        "description": "Get Spotify catalog information for several audiobooks identified by their Spotify IDs. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
        "operationId": "get-multiple-audiobooks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/audiobooks/{id}/chapters": {
      "get": {
        "tags": [
          "Audiobooks",
          "Chapters"
        ],
        "summary": "get-audiobook-chapters",
        "description": "Get Spotify catalog information about an audiobook's chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
        "operationId": "get-audiobook-chapters",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/me/audiobooks": {
      "get": {
        "tags": [
          "Audiobooks",
          "Library"
        ],
        "summary": "get-users-saved-audiobooks",
        "description": "Get a list of the audiobooks saved in the current Spotify user's 'Your Music' library.\n",
        "operationId": "get-users-saved-audiobooks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Audiobooks",
          "Library"
        ],
        "summary": "save-audiobooks-user",
        "description": "Save one or more audiobooks to the current Spotify user's library.\n",
        "operationId": "save-audiobooks-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Audiobooks",
          "Library"
        ],
        "summary": "remove-audiobooks-user",
        "description": "Remove one or more audiobooks from the Spotify user's library.\n",
        "operationId": "remove-audiobooks-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      }
    },
    "/me/audiobooks/contains": {
      "get": {
        "tags": [
          "Audiobooks",
          "Library"
        ],
        "summary": "check-users-saved-audiobooks",
        "description": "Check if one or more audiobooks are already saved in the current Spotify user's library.\n",
        "operationId": "check-users-saved-audiobooks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      }
    },
    "/browse/categories": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "get-categories",
        "description": "Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).\n",
        "operationId": "get-categories",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/browse/categories/{category_id}": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "get-a-category",
        "description": "Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).\n",
        "operationId": "get-a-category",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/chapters/{id}": {
      "get": {
        "tags": [
          "Chapters"
        ],
        "summary": "get-a-chapter",
        "description": "Get Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
        "operationId": "get-a-chapter",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/chapters": {
      "get": {
        "tags": [
          "Chapters"
        ],
        "summary": "get-several-chapters",
        "description": "Get Spotify catalog information for several audiobook chapters identified by their Spotify IDs. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
        "operationId": "get-several-chapters",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/episodes/{id}": {
      "get": {
        "tags": [
          "Episodes"
        ],
        "summary": "get-an-episode",
        "description": "Get Spotify catalog information for a single episode identified by its\nunique Spotify ID.\n",
        "operationId": "get-an-episode",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-playback-position"
            ]
          }
        ]
      }
    },
    "/episodes": {
      "get": {
        "tags": [
          "Episodes"
        ],
        "summary": "get-multiple-episodes",
        "description": "Get Spotify catalog information for several episodes based on their Spotify IDs.\n",
        "operationId": "get-multiple-episodes",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-playback-position"
            ]
          }
        ]
      }
    },
    "/me/episodes": {
      "get": {
        "tags": [
          "Episodes",
          "Library"
        ],
        "summary": "get-users-saved-episodes",
        "description": "Get a list of the episodes saved in the current Spotify user's library.<br/>\nThis API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).\n",
        "operationId": "get-users-saved-episodes",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read",
              "user-read-playback-position"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Episodes",
          "Library"
        ],
        "summary": "save-episodes-user",
        "description": "Save one or more episodes to the current user's library.<br/>\nThis API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).\n",
        "operationId": "save-episodes-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Episodes",
          "Library"
        ],
        "summary": "remove-episodes-user",
        "description": "Remove one or more episodes from the current user's library.<br/>\nThis API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).\n",
        "operationId": "remove-episodes-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      }
    },
    "/me/episodes/contains": {
      "get": {
        "tags": [
          "Episodes",
          "Library"
        ],
        "summary": "check-users-saved-episodes",
        "description": "Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.<br/>\nThis API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..\n",
        "operationId": "check-users-saved-episodes",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      }
    },
    "/recommendations/available-genre-seeds": {
      "get": {
        "tags": [
          "Genres"
        ],
        "summary": "get-recommendation-genres",
        "description": "Retrieve a list of available genres seed parameter values for [recommendations](/documentation/web-api/reference/get-recommendations).\n",
        "operationId": "get-recommendation-genres",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/markets": {
      "get": {
        "tags": [
          "Markets"
        ],
        "summary": "get-available-markets",
        "description": "Get the list of markets where Spotify is available.\n",
        "operationId": "get-available-markets",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/me/player": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "get-information-about-the-users-current-playback",
        "description": "Get information about the user’s current playback state, including track or episode, progress, and active device.\n",
        "operationId": "get-information-about-the-users-current-playback",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-playback-state"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "transfer-a-users-playback",
        "description": "Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "transfer-a-users-playback",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/devices": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "get-a-users-available-devices",
        "description": "Get information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.\n",
        "operationId": "get-a-users-available-devices",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/currently-playing": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "get-the-users-currently-playing-track",
        "description": "Get the object currently being played on the user's Spotify account.\n",
        "operationId": "get-the-users-currently-playing-track",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-currently-playing"
            ]
          }
        ]
      }
    },
    "/me/player/play": {
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "start-a-users-playback",
        "description": "Start a new context or resume current playback on the user's active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "start-a-users-playback",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/pause": {
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "pause-a-users-playback",
        "description": "Pause playback on the user's account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "pause-a-users-playback",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/next": {
      "post": {
        "tags": [
          "Player"
        ],
        "summary": "skip-users-playback-to-next-track",
        "description": "Skips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "skip-users-playback-to-next-track",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/previous": {
      "post": {
        "tags": [
          "Player"
        ],
        "summary": "skip-users-playback-to-previous-track",
        "description": "Skips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "skip-users-playback-to-previous-track",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/seek": {
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "seek-to-position-in-currently-playing-track",
        "description": "Seeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "seek-to-position-in-currently-playing-track",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/repeat": {
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "set-repeat-mode-on-users-playback",
        "description": "Set the repeat mode for the user's playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "set-repeat-mode-on-users-playback",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/volume": {
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "set-volume-for-users-playback",
        "description": "Set the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "set-volume-for-users-playback",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/shuffle": {
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "toggle-shuffle-for-users-playback",
        "description": "Toggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "toggle-shuffle-for-users-playback",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/me/player/recently-played": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "get-recently-played",
        "description": "Get tracks from the current user's recently played tracks.\n_**Note**: Currently doesn't support podcast episodes._\n",
        "operationId": "get-recently-played",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-recently-played"
            ]
          }
        ]
      }
    },
    "/me/player/queue": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "get-queue",
        "description": "Get the list of objects that make up the user's queue.\n",
        "operationId": "get-queue",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-currently-playing",
              "user-read-playback-state"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Player"
        ],
        "summary": "add-to-queue",
        "description": "Add an item to the end of the user's current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n",
        "operationId": "add-to-queue",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-modify-playback-state"
            ]
          }
        ]
      }
    },
    "/playlists/{playlist_id}": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "get-playlist",
        "description": "Get a playlist owned by a Spotify user.\n",
        "operationId": "get-playlist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      },
      "put": {
        "tags": [
          "Playlists",
          "Library"
        ],
        "summary": "change-playlist-details",
        "description": "Change a playlist's name and public/private state. (The user must, of\ncourse, own the playlist.)\n",
        "operationId": "change-playlist-details",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      }
    },
    "/playlists/{playlist_id}/tracks": {
      "get": {
        "tags": [
          "Playlists",
          "Tracks"
        ],
        "summary": "get-playlists-tracks",
        "description": "Get full details of the items of a playlist owned by a Spotify user.\n",
        "operationId": "get-playlists-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-read-private"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Playlists",
          "Tracks"
        ],
        "summary": "add-tracks-to-playlist",
        "description": "Add one or more items to a user's playlist.\n",
        "operationId": "add-tracks-to-playlist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Playlists",
          "Tracks"
        ],
        "summary": "reorder-or-replace-playlists-tracks",
        "description": "Either reorder or replace items in a playlist depending on the request's parameters.\nTo reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.\nTo replace items, include `uris` as either a query parameter or in the request's body.\nReplacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.\n<br/>\n**Note**: Replace and reorder are mutual[...]",
        "operationId": "reorder-or-replace-playlists-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Playlists",
          "Tracks"
        ],
        "summary": "remove-tracks-playlist",
        "description": "Remove one or more items from a user's playlist.\n",
        "operationId": "remove-tracks-playlist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      }
    },
    "/me/playlists": {
      "get": {
        "tags": [
          "Playlists",
          "Library"
        ],
        "summary": "get-a-list-of-current-users-playlists",
        "description": "Get a list of the playlists owned or followed by the current Spotify\nuser.\n",
        "operationId": "get-a-list-of-current-users-playlists",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-read-private"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/playlists": {
      "get": {
        "tags": [
          "Playlists",
          "Users"
        ],
        "summary": "get-list-users-playlists",
        "description": "Get a list of the playlists owned or followed by a Spotify user.\n",
        "operationId": "get-list-users-playlists",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-read-private",
              "playlist-read-collaborative"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Playlists",
          "Library"
        ],
        "summary": "create-playlist",
        "description": "Create a playlist for a Spotify user. (The playlist will be empty until\nyou [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)\nEach user is generally limited to a maximum of 11000 playlists.\n",
        "operationId": "create-playlist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      }
    },
    "/browse/featured-playlists": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "get-featured-playlists",
        "description": "Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).\n",
        "operationId": "get-featured-playlists",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/browse/categories/{category_id}/playlists": {
      "get": {
        "tags": [
          "Playlists",
          "Categories"
        ],
        "summary": "get-a-categories-playlists",
        "description": "Get a list of Spotify playlists tagged with a particular category.\n",
        "operationId": "get-a-categories-playlists",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/playlists/{playlist_id}/images": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "get-playlist-cover",
        "description": "Get the current image associated with a specific playlist.\n",
        "operationId": "get-playlist-cover",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      },
      "put": {
        "tags": [
          "Playlists"
        ],
        "summary": "upload-custom-playlist-cover",
        "description": "Replace the image used to represent a specific playlist.\n",
        "operationId": "upload-custom-playlist-cover",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "ugc-image-upload",
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      }
    },
    "/search": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "search",
        "description": "Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks\nthat match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
        "operationId": "search",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/shows/{id}": {
      "get": {
        "tags": [
          "Shows"
        ],
        "summary": "get-a-show",
        "description": "Get Spotify catalog information for a single show identified by its\nunique Spotify ID.\n",
        "operationId": "get-a-show",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-playback-position"
            ]
          }
        ]
      }
    },
    "/shows": {
      "get": {
        "tags": [
          "Shows"
        ],
        "summary": "get-multiple-shows",
        "description": "Get Spotify catalog information for several shows based on their Spotify IDs.\n",
        "operationId": "get-multiple-shows",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/shows/{id}/episodes": {
      "get": {
        "tags": [
          "Shows",
          "Episodes"
        ],
        "summary": "get-a-shows-episodes",
        "description": "Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.\n",
        "operationId": "get-a-shows-episodes",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-playback-position"
            ]
          }
        ]
      }
    },
    "/me/shows": {
      "get": {
        "tags": [
          "Shows",
          "Library"
        ],
        "summary": "get-users-saved-shows",
        "description": "Get a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.\n",
        "operationId": "get-users-saved-shows",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Shows",
          "Library"
        ],
        "summary": "save-shows-user",
        "description": "Save one or more shows to current Spotify user's library.\n",
        "operationId": "save-shows-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Shows",
          "Library"
        ],
        "summary": "remove-shows-user",
        "description": "Delete one or more shows from current Spotify user's library.\n",
        "operationId": "remove-shows-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      }
    },
    "/me/shows/contains": {
      "get": {
        "tags": [
          "Shows",
          "Library"
        ],
        "summary": "check-users-saved-shows",
        "description": "Check if one or more shows is already saved in the current Spotify user's library.\n",
        "operationId": "check-users-saved-shows",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      }
    },
    "/tracks/{id}": {
      "get": {
        "tags": [
          "Tracks"
        ],
        "summary": "get-track",
        "description": "Get Spotify catalog information for a single track identified by its\nunique Spotify ID.\n",
        "operationId": "get-track",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/tracks": {
      "get": {
        "tags": [
          "Tracks"
        ],
        "summary": "get-several-tracks",
        "description": "Get Spotify catalog information for multiple tracks based on their Spotify IDs.\n",
        "operationId": "get-several-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/me/tracks": {
      "get": {
        "tags": [
          "Tracks",
          "Library"
        ],
        "summary": "get-users-saved-tracks",
        "description": "Get a list of the songs saved in the current Spotify user's 'Your Music' library.\n",
        "operationId": "get-users-saved-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Tracks",
          "Library"
        ],
        "summary": "save-tracks-user",
        "description": "Save one or more tracks to the current user's 'Your Music' library.\n",
        "operationId": "save-tracks-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Tracks",
          "Library"
        ],
        "summary": "remove-tracks-user",
        "description": "Remove one or more tracks from the current user's 'Your Music' library.\n",
        "operationId": "remove-tracks-user",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-modify"
            ]
          }
        ]
      }
    },
    "/me/tracks/contains": {
      "get": {
        "tags": [
          "Tracks",
          "Library"
        ],
        "summary": "check-users-saved-tracks",
        "description": "Check if one or more tracks is already saved in the current Spotify user's 'Your Music' library.\n",
        "operationId": "check-users-saved-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-library-read"
            ]
          }
        ]
      }
    },
    "/audio-features": {
      "get": {
        "tags": [
          "Tracks"
        ],
        "summary": "get-several-audio-features",
        "description": "Get audio features for multiple tracks based on their Spotify IDs.\n",
        "operationId": "get-several-audio-features",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/audio-features/{id}": {
      "get": {
        "tags": [
          "Tracks"
        ],
        "summary": "get-audio-features",
        "description": "Get audio feature information for a single track identified by its unique\nSpotify ID.\n",
        "operationId": "get-audio-features",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/audio-analysis/{id}": {
      "get": {
        "tags": [
          "Tracks"
        ],
        "summary": "get-audio-analysis",
        "description": "Get a low-level audio analysis for a track in the Spotify catalog. The audio analysis describes the track’s structure and musical content, including rhythm, pitch, and timbre.\n",
        "operationId": "get-audio-analysis",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/recommendations": {
      "get": {
        "tags": [
          "Tracks"
        ],
        "summary": "get-recommendations",
        "description": "Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.\n\nFor artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.\n",
        "operationId": "get-recommendations",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/me": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get-current-users-profile",
        "description": "Get detailed profile information about the current user (including the\ncurrent user's username).\n",
        "operationId": "get-current-users-profile",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-read-private",
              "user-read-email"
            ]
          }
        ]
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get-users-profile",
        "description": "Get public profile information about a Spotify user.\n",
        "operationId": "get-users-profile",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/playlists/{playlist_id}/followers": {
      "put": {
        "tags": [
          "Users",
          "Playlists"
        ],
        "summary": "follow-playlist",
        "description": "Add the current user as a follower of a playlist.\n",
        "operationId": "follow-playlist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Users",
          "Playlists"
        ],
        "summary": "unfollow-playlist",
        "description": "Remove the current user as a follower of a playlist.\n",
        "operationId": "unfollow-playlist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "playlist-modify-public",
              "playlist-modify-private"
            ]
          }
        ]
      }
    },
    "/me/following": {
      "get": {
        "tags": [
          "Users",
          "Library",
          "Artists"
        ],
        "summary": "get-followed",
        "description": "Get the current user's followed artists.\n",
        "operationId": "get-followed",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-follow-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Users",
          "Artists",
          "Library"
        ],
        "summary": "follow-artists-users",
        "description": "Add the current user as a follower of one or more artists or other Spotify users.\n",
        "operationId": "follow-artists-users",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-follow-modify"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Users",
          "Artists",
          "Library"
        ],
        "summary": "unfollow-artists-users",
        "description": "Remove the current user as a follower of one or more artists or other Spotify users.\n",
        "operationId": "unfollow-artists-users",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-follow-modify"
            ]
          }
        ]
      }
    },
    "/me/following/contains": {
      "get": {
        "tags": [
          "Users",
          "Artists",
          "Library"
        ],
        "summary": "check-current-user-follows",
        "description": "Check to see if the current user is following one or more artists or other Spotify users.\n",
        "operationId": "check-current-user-follows",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-follow-read"
            ]
          }
        ]
      }
    },
    "/playlists/{playlist_id}/followers/contains": {
      "get": {
        "tags": [
          "Users",
          "Playlists"
        ],
        "summary": "check-if-user-follows-playlist",
        "description": "Check to see if one or more Spotify users are following a specified playlist.\n",
        "operationId": "check-if-user-follows-playlist",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": []
          }
        ]
      }
    },
    "/me/top/artists": {
      "get": {
        "tags": [
          "Users",
          "Artists",
          "Library"
        ],
        "summary": "get-users-top-artists",
        "description": "Get the current user's top artists based on calculated affinity.\n",
        "operationId": "get-users-top-artists",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-top-read"
            ]
          }
        ]
      }
    },
    "/me/top/tracks": {
      "get": {
        "tags": [
          "Users",
          "Tracks",
          "Library"
        ],
        "summary": "get-users-top-tracks",
        "description": "Get the current user's top tracks based on calculated affinity.\n",
        "operationId": "get-users-top-tracks",
        "deprecated": false,
        "security": [
          {
            "oauth_2_0": [
              "user-top-read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth_2_0": {
        "type": "oauth2",
        "description": "Spotify supports OAuth 2.0 for authenticating all API requests.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.spotify.com/authorize",
            "tokenUrl": "https://accounts.spotify.com/api/token",
            "scopes": {
              "app-remote-control": "Communicate with the Spotify app on your device.\n",
              "playlist-read-private": "Access your private playlists.\n",
              "playlist-read-collaborative": "Access your collaborative playlists.\n",
              "playlist-modify-public": "Manage your public playlists.\n",
              "playlist-modify-private": "Manage your private playlists.\n",
              "user-library-read": "Access your saved content.\n",
              "user-library-modify": "Manage your saved content.\n",
              "user-read-private": "Access your subscription details.\n",
              "user-read-email": "Get your real email address.\n",
              "user-follow-read": "Access your followers and who you are following.\n",
              "user-follow-modify": "Manage your saved content.\n",
              "user-top-read": "Read your top artists and content.\n",
              "user-read-playback-position": "Read your position in content you have played.\n",
              "user-read-playback-state": "Read your currently playing content and Spotify Connect devices information.\n",
              "user-read-recently-played": "Access your recently played items.\n",
              "user-read-currently-playing": "Read your currently playing content.\n",
              "user-modify-playback-state": "Control playback on your Spotify clients and Spotify Connect devices.\n",
              "ugc-image-upload": "Upload images to Spotify on your behalf.\n",
              "streaming": "Play content and control playback on your other devices.\n"
            }
          }
        }
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "Albums"
    },
    {
      "name": "Artists"
    },
    {
      "name": "Audiobooks"
    },
    {
      "name": "Categories"
    },
    {
      "name": "Chapters"
    },
    {
      "name": "Episodes"
    },
    {
      "name": "Library"
    },
    {
      "name": "Genres"
    },
    {
      "name": "Markets"
    },
    {
      "name": "Player"
    },
    {
      "name": "Playlists"
    },
    {
      "name": "Search"
    },
    {
      "name": "Shows"
    },
    {
      "name": "Tracks"
    },
    {
      "name": "Users"
    }
  ]
}