FORMAT: 1A
HOST: http://1password.local

# 1Password Connect
REST API interface for 1Password Connect.

## Authentication
This API uses JSON Web Tokens for its authentication.

The parameters that are needed to be sent for this type of authentication are as follows:
+ `JWTHeaderName`
+ `JWTAcquireURL`
+ `JWTDestroyURL`

# Group Items

Access and manage items inside 1Password Vaults

## Vaults Items By VaultUuid [/vaults/{vaultUuid}/items{?filter}]

+ Parameters
    + vaultUuid (string, required)

        The UUID of the Vault to fetch Items from


### GetVaultItems [GET]
+ Parameters
    + filter (string, optional)

        Filter the Item collection based on Item name using SCIM eq filter

        + Sample: title eq "Some Item Name"

+ Response 200 (application/json)

        OK

    + Attributes (array[Item])



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 404 (application/json)

        Vault not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} not found","status":404}



## Vaults Items By VaultUuid [/vaults/{vaultUuid}/items]

+ Parameters
    + vaultUuid (string, required)

        The UUID of the Vault to create an Item in


### CreateVaultItem [POST]

+ Request (<<Add Header Value>>)

    + Attributes (FullItem)



+ Response 200 (application/json)

        OK

    + Attributes (FullItem)



+ Response 400 (application/json)

        Unable to create item due to invalid input

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid item category","status":400}


+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 403 (application/json)

        Unauthorized access

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} is not in scope","status":403}


+ Response 404 (application/json)

        Item not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} not found","status":404}



## Vaults Items By VaultUuid And ItemUuid [/vaults/{vaultUuid}/items/{itemUuid}]

+ Parameters
    + vaultUuid (string, required)

        The UUID of the Vault the item is in

    + itemUuid (string, required)

        The UUID of the Item to update


### DeleteVaultItem [DELETE]

+ Response 204 

        Successfully deleted an item




+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 403 (application/json)

        Unauthorized access

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} is not in scope","status":403}


+ Response 404 (application/json)

        Item not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} not found","status":404}


### GetVaultItemById [GET]

+ Response 200 (application/json)

        OK

    + Attributes (FullItem)



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 403 (application/json)

        Unauthorized access

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} is not in scope","status":403}


+ Response 404 (application/json)

        Item not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"item {itemUuid} not found","status":404}


### PatchVaultItem [PATCH]
Applies a modified [RFC6902 JSON Patch](https://tools.ietf.org/html/rfc6902) document to an Item or ItemField. This endpoint only supports `add`, `remove` and `replace` operations.

When modifying a specific ItemField, the ItemField's ID in the `path` attribute of the operation object: `/fields/{fieldId}`

+ Request (<<Add Header Value>>)

    + Attributes (array[Patch])



+ Response 200 (application/json)

        OK - Item updated. If no Patch operations were provided, Item is unmodified.

    + Attributes (FullItem)



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 403 (application/json)

        Unauthorized access

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} is not in scope","status":403}


+ Response 404 (application/json)

        Item not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"item {itemUuid} not found","status":404}


### UpdateVaultItem [PUT]

+ Request (<<Add Header Value>>)

    + Attributes (FullItem)



+ Response 200 (application/json)

        OK

    + Attributes (FullItem)



+ Response 400 (application/json)

        Unable to create item due to invalid input

    + Attributes (ErrorResponse)


    + Body

            {"message":"The item doesn't have a {example field name} field.","status":400}


+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 403 (application/json)

        Unauthorized access

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} is not in scope","status":403}


+ Response 404 (application/json)

        Item not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"item {itemUuid} not found","status":404}




# Group Vaults

Access 1Password Vaults

## Vaults [/vaults{?filter}]

### GetVaults [GET]
+ Parameters
    + filter (string, optional)

        Filter the Vault collection based on Vault name using SCIM eq filter

        + Sample: name eq "Some Vault Name"

+ Response 200 (application/json)

        OK

    + Attributes (array[Vault])



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}



## Vaults By VaultUuid [/vaults/{vaultUuid}]

+ Parameters
    + vaultUuid (string, required)

        The UUID of the Vault to fetch Items from


### GetVaultById [GET]

+ Response 200 (application/json)

        OK

    + Attributes (Vault)



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 403 (application/json)

        Unauthorized access

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} is not in scope","status":403}


+ Response 404 (application/json)

        Vault not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {itemUuid} not found","status":404}




# Group Activity

Access API Request Activity

## Activity [/activity{?limit,offset}]

### GetApiActivity [GET]
+ Parameters
    + limit (number, optional) -

        How many API Events should be retrieved in a single request.

        + Default: 50
        + Sample: 10
    + offset (number, optional) -

        How far into the collection of API Events should the response start

        + Default: 0
        + Sample: 50

+ Response 200 (application/json)

        OK

    + Attributes (array[APIRequest])



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}




# Group Health

## Health [/health]

### GetServerHealth [GET]

+ Response 200 (application/json)

        OK

    + Attributes (Health Response)


    + Body

            {"dependencies":[{"service":"sync","status":"TOKEN_NEEDED"},{"message":"Connected to./1password.sqlite","service":"sqlite","status":"ACTIVE"}],"name":"1Password Connect API","version":"1.2.1"}



## Heartbeat [/heartbeat]

### GetHeartbeat [GET]

+ Response 200 (text/plain)

        OK

    + Attributes (string)





# Group Metrics

## Metrics [/metrics]

### GetPrometheusMetrics [GET]
See Prometheus documentation for a complete data model.

+ Response 200 (text/plain)

        Successfully returned Prometheus metrics

    + Attributes (string)





# Group Files

## Vaults Items Files By VaultUuid [/vaults/{vaultUuid}/items/{itemUuid}/files{?inline_files}]

+ Parameters
    + vaultUuid (string, required)

        The UUID of the Vault to fetch Items from

    + itemUuid (string, required)

        The UUID of the Item to fetch files from


### GetItemFiles [GET]
+ Parameters
    + inline_files (boolean, optional)

        Tells server to return the base64-encoded file contents in the response.

        + Sample: true

+ Response 200 (application/json)

        OK

    + Attributes (array[File])



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 404 (application/json)

        Item not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"item {itemUuid} not found","status":404}


+ Response 413 (application/json)

        File content too large to display

    + Attributes (ErrorResponse)


    + Body

            {"message":"File is too large to inline in request. Use the /v1/vaults/{vaultUUID}/items/{itemUUID}/files/{fileUUID}/content endpoint instead.","status":413}



## Vaults Items Files FileUuid By VaultUuid [/vaults/{vaultUuid}/items/{itemUuid}/files/{fileUuid}{?inline_files}]

+ Parameters
    + vaultUuid (string, required)

        The UUID of the Vault to fetch Item from

    + itemUuid (string, required)

        The UUID of the Item to fetch File from

    + fileUuid (string, required)

        The UUID of the File to fetch


### GetDetailsOfFileById [GET]
+ Parameters
    + inline_files (boolean, optional)

        Tells server to return the base64-encoded file contents in the response.

        + Sample: true

+ Response 200 (application/json)

        OK

    + Attributes (File)



+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 403 (application/json)

        Unauthorized access

    + Attributes (ErrorResponse)


    + Body

            {"message":"vault {vaultUuid} is not in scope","status":403}


+ Response 404 (application/json)

        File not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"file {fileUuid} not found","status":404}


+ Response 413 (application/json)

        File content too large to display

    + Attributes (ErrorResponse)


    + Body

            {"message":"File is too large to inline in request. Use the /v1/vaults/{vaultUUID}/items/{itemUUID}/files/{fileUUID}/content endpoint instead.","status":413}



## Vaults Items Files FileUuid Content [/vaults/{vaultUuid}/items/{itemUuid}/files/{fileUuid}/content]

+ Parameters
    + vaultUuid (string, required)

        The UUID of the Vault the item is in

    + itemUuid (string, required)

        The UUID of the Item the File is in

    + fileUuid (string, required)

        UUID of the file to get content from


### DownloadFileByID [GET]

+ Response 200 (application/octet-stream)

        Success




+ Response 401 (application/json)

        Invalid or missing token

    + Attributes (ErrorResponse)


    + Body

            {"message":"Invalid token signature","status":401}


+ Response 404 (application/json)

        File not found

    + Attributes (ErrorResponse)


    + Body

            {"message":"file {fileUuid} not found","status":404}




# Data Structures

## APIRequest (object)
Represents a request that was made to the API. Including what Token was used and what resource was accessed.

### Properties
+ `action` (enum[string], optional) 
    + `READ`
    + `CREATE`
    + `UPDATE`
    + `DELETE`
+ `actor` (Actor, optional) 
+ `requestId` (string, optional) - The unique id used to identify a single request.
+ `resource` (Resource, optional) 
+ `result` (enum[string], optional) 
    + `SUCCESS`
    + `DENY`
+ `timestamp` (string, optional) - The time at which the request was processed by the server.


## ErrorResponse (object)


### Properties
+ `message` (string, optional) - A message detailing the error
+ `status` (number, optional) - HTTP Status Code


## Field (object)


### Properties
+ `entropy` (number, optional) - For fields with a purpose of `PASSWORD` this is the entropy of the value
+ `generate`: `false` (boolean, optional) - If value is not present then a new value should be generated for this field
+ `id` (string, required) 
+ `label` (string, optional) 
+ `purpose` (enum[string], optional) - Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types.
    + `USERNAME`
    + `PASSWORD`
    + `NOTES`
+ `recipe` (GeneratorRecipe, optional) - The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value
+ `section` (Section, optional) 
+ `type` (enum[string], required) 
    + `STRING`
    + `EMAIL`
    + `CONCEALED`
    + `URL`
    + `TOTP`
    + `DATE`
    + `MONTH_YEAR`
    + `MENU`
+ `value` (string, optional) 


## File (object)


### Properties
+ `content` (string, optional) - Base64-encoded contents of the file. Only set if size <= OP_MAX_INLINE_FILE_SIZE_KB kb and `inline_files` is set to `true`.
+ `content_path` (string, optional) - Path of the Connect API that can be used to download the contents of this file.
+ `id` (string, optional) - ID of the file
+ `name` (string, optional) - Name of the file
+ `section` (Section1, optional) - For files that are in a section, this field describes the section.
+ `size` (number, optional) - Size in bytes of the file


## FullItem (object)


### Properties
+ `category` (enum[string], required) 
    + `LOGIN`
    + `PASSWORD`
    + `API_CREDENTIAL`
    + `SERVER`
    + `DATABASE`
    + `CREDIT_CARD`
    + `MEMBERSHIP`
    + `PASSPORT`
    + `SOFTWARE_LICENSE`
    + `OUTDOOR_LICENSE`
    + `SECURE_NOTE`
    + `WIRELESS_ROUTER`
    + `BANK_ACCOUNT`
    + `DRIVER_LICENSE`
    + `IDENTITY`
    + `REWARD_PROGRAM`
    + `DOCUMENT`
    + `EMAIL_ACCOUNT`
    + `SOCIAL_SECURITY_NUMBER`
    + `MEDICAL_RECORD`
    + `SSH_KEY`
    + `CUSTOM`
+ `createdAt` (string, optional) 
+ `favorite`: `false` (boolean, optional) 
+ `id` (string, optional) 
+ `lastEditedBy` (string, optional) 
+ `state` (enum[string], optional) 
    + `ARCHIVED`
    + `DELETED`
+ `tags` (array[string], optional) 
+ `title` (string, optional) 
+ `updatedAt` (string, optional) 
+ `urls` (array[Url], optional) 
+ `vault` (Vault1, required) 
+ `version` (number, optional) 
+ `fields` (array[Field], optional) 
+ `files` (array[File], optional) 
+ `sections` (array[Section2], optional) 


## GeneratorRecipe (object)
The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value

### Properties
+ `characterSets` (array, optional) 
    + (enum[string])
        + Members
            + `LETTERS`
            + `DIGITS`
            + `SYMBOLS`
+ `excludeCharacters`: `abc1` (string, optional) - List of all characters that should be excluded from generated passwords.
+ `length`: `32` (number, optional) - Length of the generated value


## Item (object)


### Properties
+ `category` (enum[string], required) 
    + `LOGIN`
    + `PASSWORD`
    + `API_CREDENTIAL`
    + `SERVER`
    + `DATABASE`
    + `CREDIT_CARD`
    + `MEMBERSHIP`
    + `PASSPORT`
    + `SOFTWARE_LICENSE`
    + `OUTDOOR_LICENSE`
    + `SECURE_NOTE`
    + `WIRELESS_ROUTER`
    + `BANK_ACCOUNT`
    + `DRIVER_LICENSE`
    + `IDENTITY`
    + `REWARD_PROGRAM`
    + `DOCUMENT`
    + `EMAIL_ACCOUNT`
    + `SOCIAL_SECURITY_NUMBER`
    + `MEDICAL_RECORD`
    + `SSH_KEY`
    + `CUSTOM`
+ `createdAt` (string, optional) 
+ `favorite`: `false` (boolean, optional) 
+ `id` (string, optional) 
+ `lastEditedBy` (string, optional) 
+ `state` (enum[string], optional) 
    + `ARCHIVED`
    + `DELETED`
+ `tags` (array[string], optional) 
+ `title` (string, optional) 
+ `updatedAt` (string, optional) 
+ `urls` (array[Url], optional) 
+ `vault` (Vault1, required) 
+ `version` (number, optional) 


## ServiceDependency (object)
The state of a registered server dependency.

### Properties
+ `message` (string, optional) - Human-readable message for explaining the current state.
+ `service` (string, optional) 
+ `status` (string, optional) 


## Vault (object)


### Properties
+ `attributeVersion` (number, optional) - The vault version
+ `contentVersion` (number, optional) - The version of the vault contents
+ `createdAt` (string, optional) 
+ `description` (string, optional) 
+ `id` (string, optional) 
+ `items` (number, optional) - Number of active items in the vault
+ `name` (string, optional) 
+ `type` (enum[string], optional) 
    + `USER_CREATED`
    + `PERSONAL`
    + `EVERYONE`
    + `TRANSFER`
+ `updatedAt` (string, optional) 


## Actor (object)


### Properties
+ `account` (string, optional) 
+ `id` (string, optional) 
+ `jti` (string, optional) 
+ `requestIp` (string, optional) 
+ `userAgent` (string, optional) 


## Health Response (object)


### Properties
+ `dependencies` (array[ServiceDependency], optional) 
+ `name` (string, required) 
+ `version` (string, required) - The Connect server's version


## Item2 (object)


### Properties
+ `id` (string, optional) 


## Patch (object)


### Properties
+ `op` (enum[string], required) 
    + `add`
    + `remove`
    + `replace`
+ `path`: `/fields/06gnn2b95example10q91512p5/label` (string, required) - An RFC6901 JSON Pointer pointing to the Item document, an Item Attribute, and Item Field by Field ID, or an Item Field Attribute
+ `value` (object, optional) 


## Resource (object)


### Properties
+ `item` (Item2, optional) 
+ `itemVersion` (number, optional) 
+ `type` (enum[string], optional) 
    + `ITEM`
    + `VAULT`
+ `vault` (Vault3, optional) 


## Section (object)


### Properties
+ `id` (string, optional) 


## Section1 (object)
For files that are in a section, this field describes the section.

### Properties
+ `id` (string, optional) 


## Section2 (object)


### Properties
+ `id` (string, optional) 
+ `label` (string, optional) 


## Url (object)


### Properties
+ `href` (string, required) 
+ `label` (string, optional) 
+ `primary` (boolean, optional) 


## Vault1 (object)


### Properties
+ `id` (string, required) 


## Vault3 (object)


### Properties
+ `id` (string, optional) 

