#%RAML 1.0
title: 1Password Connect
version: 1.5.7
baseUri: http://1password.local
baseUriParameters: {}
protocols:
- HTTP
documentation:
- title: 1Password Connect
  content: REST API interface for 1Password Connect.
securitySchemes: {}
securedBy: []
types:
  APIRequest:
    displayName: APIRequest
    description: Represents a request that was made to the API. Including what Token was used and what resource was accessed.
    type: object
    properties:
      action:
        required: false
        displayName: action
        type: string
        enum:
        - READ
        - CREATE
        - UPDATE
        - DELETE
      actor:
        required: false
        displayName: actor
        type: Actor
      requestId:
        required: false
        displayName: requestId
        description: The unique id used to identify a single request.
        type: any
      resource:
        required: false
        displayName: resource
        type: Resource
      result:
        required: false
        displayName: result
        type: string
        enum:
        - SUCCESS
        - DENY
      timestamp:
        required: false
        displayName: timestamp
        description: The time at which the request was processed by the server.
        type: datetime
  ErrorResponse:
    displayName: ErrorResponse
    type: object
    properties:
      message:
        required: false
        displayName: message
        description: A message detailing the error
        type: string
      status:
        required: false
        displayName: status
        description: HTTP Status Code
        type: integer
        format: int32
  Field:
    displayName: Field
    type: object
    properties:
      entropy:
        required: false
        displayName: entropy
        description: For fields with a purpose of `PASSWORD` this is the entropy of the value
        type: number
        format: double
      generate:
        required: false
        default: 'false'
        displayName: generate
        description: If value is not present then a new value should be generated for this field
        type: boolean
      id:
        required: true
        displayName: id
        type: string
      label:
        required: false
        displayName: label
        type: string
      purpose:
        required: false
        displayName: purpose
        description: Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types.
        type: string
        enum:
        - USERNAME
        - PASSWORD
        - NOTES
      recipe:
        required: false
        displayName: recipe
        description: The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value
        type: GeneratorRecipe
      section:
        required: false
        displayName: section
        type: Section
      type:
        required: true
        default: STRING
        displayName: type
        type: string
        enum:
        - STRING
        - EMAIL
        - CONCEALED
        - URL
        - TOTP
        - DATE
        - MONTH_YEAR
        - MENU
      value:
        required: false
        displayName: value
        type: string
  File:
    example:
      value:
        content: VGhlIGZ1dHVyZSBiZWxvbmdzIHRvIHRoZSBjdXJpb3VzLgo=
        content_path: v1/vaults/ionaiwtdvgclrixbt6ztpqcxnq/items/p7eflcy7f5mk7vg6zrzf5rjjyu/files/6r65pjq33banznomn7q22sj44e/content
        id: 6r65pjq33banznomn7q22sj44e
        name: foo.txt
        size: 35
    displayName: File
    type: object
    properties:
      content:
        required: false
        displayName: content
        description: Base64-encoded contents of the file. Only set if size <= OP_MAX_INLINE_FILE_SIZE_KB kb and `inline_files` is set to `true`.
        type: string
      content_path:
        required: false
        displayName: content_path
        description: Path of the Connect API that can be used to download the contents of this file.
        type: string
      id:
        required: false
        displayName: id
        description: ID of the file
        type: string
      name:
        required: false
        displayName: name
        description: Name of the file
        type: string
      section:
        required: false
        displayName: section
        description: For files that are in a section, this field describes the section.
        type: Section1
      size:
        required: false
        displayName: size
        description: Size in bytes of the file
        type: integer
        format: int32
  FullItem:
    displayName: FullItem
    type: object
    properties:
      category:
        required: true
        displayName: category
        type: string
        enum:
        - LOGIN
        - PASSWORD
        - API_CREDENTIAL
        - SERVER
        - DATABASE
        - CREDIT_CARD
        - MEMBERSHIP
        - PASSPORT
        - SOFTWARE_LICENSE
        - OUTDOOR_LICENSE
        - SECURE_NOTE
        - WIRELESS_ROUTER
        - BANK_ACCOUNT
        - DRIVER_LICENSE
        - IDENTITY
        - REWARD_PROGRAM
        - DOCUMENT
        - EMAIL_ACCOUNT
        - SOCIAL_SECURITY_NUMBER
        - MEDICAL_RECORD
        - SSH_KEY
        - CUSTOM
      createdAt:
        required: false
        displayName: createdAt
        type: datetime
      favorite:
        required: false
        default: 'false'
        displayName: favorite
        type: boolean
      id:
        required: false
        displayName: id
        type: string
        pattern: ^[\da-z]{26}$
      lastEditedBy:
        required: false
        displayName: lastEditedBy
        type: string
      state:
        required: false
        displayName: state
        type: string
        enum:
        - ARCHIVED
        - DELETED
      tags:
        required: false
        displayName: tags
        type: array
        items:
          type: string
      title:
        required: false
        displayName: title
        type: string
      updatedAt:
        required: false
        displayName: updatedAt
        type: datetime
      urls:
        required: false
        example:
          value:
          - href: https://example.com
            primary: true
          - href: https://example.org
        displayName: urls
        type: array
        items:
          type: Url
      vault:
        required: true
        displayName: vault
        type: Vault1
      version:
        required: false
        displayName: version
        type: integer
        format: int32
      fields:
        required: false
        displayName: fields
        type: array
        items:
          type: Field
      files:
        required: false
        displayName: files
        type: array
        items:
          type: File
      sections:
        required: false
        displayName: sections
        type: array
        items:
          type: Section2
  GeneratorRecipe:
    displayName: GeneratorRecipe
    description: The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value
    type: object
    properties:
      characterSets:
        required: false
        displayName: characterSets
        type: array
        uniqueItems: true
        items:
          type: string
          enum:
          - LETTERS
          - DIGITS
          - SYMBOLS
      excludeCharacters:
        required: false
        example:
          value: abc1
        displayName: excludeCharacters
        description: List of all characters that should be excluded from generated passwords.
        type: string
      length:
        required: false
        default: '32'
        displayName: length
        description: Length of the generated value
        type: integer
        minimum: 1
        maximum: 64
        format: int32
  Item:
    displayName: Item
    type: object
    properties:
      category:
        required: true
        displayName: category
        type: string
        enum:
        - LOGIN
        - PASSWORD
        - API_CREDENTIAL
        - SERVER
        - DATABASE
        - CREDIT_CARD
        - MEMBERSHIP
        - PASSPORT
        - SOFTWARE_LICENSE
        - OUTDOOR_LICENSE
        - SECURE_NOTE
        - WIRELESS_ROUTER
        - BANK_ACCOUNT
        - DRIVER_LICENSE
        - IDENTITY
        - REWARD_PROGRAM
        - DOCUMENT
        - EMAIL_ACCOUNT
        - SOCIAL_SECURITY_NUMBER
        - MEDICAL_RECORD
        - SSH_KEY
        - CUSTOM
      createdAt:
        required: false
        displayName: createdAt
        type: datetime
      favorite:
        required: false
        default: 'false'
        displayName: favorite
        type: boolean
      id:
        required: false
        displayName: id
        type: string
        pattern: ^[\da-z]{26}$
      lastEditedBy:
        required: false
        displayName: lastEditedBy
        type: string
      state:
        required: false
        displayName: state
        type: string
        enum:
        - ARCHIVED
        - DELETED
      tags:
        required: false
        displayName: tags
        type: array
        items:
          type: string
      title:
        required: false
        displayName: title
        type: string
      updatedAt:
        required: false
        displayName: updatedAt
        type: datetime
      urls:
        required: false
        example:
          value:
          - href: https://example.com
            primary: true
          - href: https://example.org
        displayName: urls
        type: array
        items:
          type: Url
      vault:
        required: true
        displayName: vault
        type: Vault1
      version:
        required: false
        displayName: version
        type: integer
        format: int32
  ServiceDependency:
    displayName: ServiceDependency
    description: The state of a registered server dependency.
    type: object
    properties:
      message:
        required: false
        displayName: message
        description: Human-readable message for explaining the current state.
        type: string
      service:
        required: false
        displayName: service
        type: string
      status:
        required: false
        displayName: status
        type: string
  Vault:
    displayName: Vault
    type: object
    properties:
      attributeVersion:
        required: false
        displayName: attributeVersion
        description: The vault version
        type: integer
        format: int32
      contentVersion:
        required: false
        displayName: contentVersion
        description: The version of the vault contents
        type: integer
        format: int32
      createdAt:
        required: false
        displayName: createdAt
        type: datetime
      description:
        required: false
        displayName: description
        type: string
      id:
        required: false
        displayName: id
        type: string
        pattern: ^[\da-z]{26}$
      items:
        required: false
        displayName: items
        description: Number of active items in the vault
        type: integer
        format: int32
      name:
        required: false
        displayName: name
        type: string
      type:
        required: false
        displayName: type
        type: string
        enum:
        - USER_CREATED
        - PERSONAL
        - EVERYONE
        - TRANSFER
      updatedAt:
        required: false
        displayName: updatedAt
        type: datetime
  Actor:
    displayName: Actor
    type: object
    properties:
      account:
        required: false
        displayName: account
        type: string
      id:
        required: false
        displayName: id
        type: any
      jti:
        required: false
        displayName: jti
        type: string
      requestIp:
        required: false
        displayName: requestIp
        type: string
      userAgent:
        required: false
        displayName: userAgent
        type: string
  HealthResponse:
    displayName: HealthResponse
    type: object
    properties:
      dependencies:
        required: false
        displayName: dependencies
        type: array
        items:
          type: ServiceDependency
      name:
        required: true
        displayName: name
        type: string
      version:
        required: true
        displayName: version
        description: The Connect server's version
        type: string
  Item2:
    displayName: Item2
    type: object
    properties:
      id:
        required: false
        displayName: id
        type: string
        pattern: ^[\da-z]{26}$
  Patch:
    displayName: Patch
    type: object
    properties:
      op:
        required: true
        displayName: op
        type: string
        enum:
        - add
        - remove
        - replace
      path:
        required: true
        example:
          value: /fields/06gnn2b95example10q91512p5/label
        displayName: path
        description: An RFC6901 JSON Pointer pointing to the Item document, an Item Attribute, and Item Field by Field ID, or an Item Field Attribute
        type: string
      value:
        required: false
        displayName: value
        type: object
        properties: {}
  Resource:
    displayName: Resource
    type: object
    properties:
      item:
        required: false
        displayName: item
        type: Item2
      itemVersion:
        required: false
        displayName: itemVersion
        type: integer
        format: int32
      type:
        required: false
        displayName: type
        type: string
        enum:
        - ITEM
        - VAULT
      vault:
        required: false
        displayName: vault
        type: Vault3
  Section:
    displayName: Section
    type: object
    properties:
      id:
        required: false
        displayName: id
        type: string
  Section1:
    displayName: Section1
    description: For files that are in a section, this field describes the section.
    type: object
    properties:
      id:
        required: false
        displayName: id
        type: string
  Section2:
    displayName: Section2
    type: object
    properties:
      id:
        required: false
        displayName: id
        type: string
      label:
        required: false
        displayName: label
        type: string
  Url:
    displayName: Url
    type: object
    properties:
      href:
        required: true
        displayName: href
        type: string
      label:
        required: false
        displayName: label
        type: string
      primary:
        required: false
        displayName: primary
        type: boolean
  Vault1:
    displayName: Vault1
    type: object
    properties:
      id:
        required: true
        displayName: id
        type: string
        pattern: ^[\da-z]{26}$
  Vault3:
    displayName: Vault3
    type: object
    properties:
      id:
        required: false
        displayName: id
        type: string
        pattern: ^[\da-z]{26}$
/vaults:
  get:
    displayName: GetVaults
    description: ''
    securedBy:
    - ConnectToken
    queryParameters:
      filter:
        required: false
        example:
          value: name eq "Some Vault Name"
        displayName: filter
        description: Filter the Vault collection based on Vault name using SCIM eq filter
        type: string
    responses:
      '200':
        description: OK
        body:
          application/json:
            displayName: response200
            description: ''
            type: array
            items:
              type: Vault
      '401':
        description: Invalid or missing token
        body:
          application/json:
            example:
              value:
                message: Invalid token signature
                status: 401
            displayName: response401
            description: ''
            type: ErrorResponse
  /{vaultUuid}:
    uriParameters:
      vaultUuid:
        required: true
        displayName: vaultUuid
        description: The UUID of the Vault to fetch Items from
        type: string
        pattern: ^[\da-z]{26}$
    get:
      displayName: GetVaultById
      description: ''
      securedBy:
      - ConnectToken
      responses:
        '200':
          description: OK
          body:
            application/json:
              displayName: response200
              description: ''
              type: Vault
        '401':
          description: Invalid or missing token
          body:
            application/json:
              example:
                value:
                  message: Invalid token signature
                  status: 401
              displayName: response401
              description: ''
              type: ErrorResponse
        '403':
          description: Unauthorized access
          body:
            application/json:
              example:
                value:
                  message: vault {vaultUuid} is not in scope
                  status: 403
              displayName: response403
              description: ''
              type: ErrorResponse
        '404':
          description: Vault not found
          body:
            application/json:
              example:
                value:
                  message: vault {itemUuid} not found
                  status: 404
              displayName: response404
              description: ''
              type: ErrorResponse
    /items:
      get:
        displayName: GetVaultItems
        description: ''
        securedBy:
        - ConnectToken
        queryParameters:
          filter:
            required: false
            example:
              value: title eq "Some Item Name"
            displayName: filter
            description: Filter the Item collection based on Item name using SCIM eq filter
            type: string
        responses:
          '200':
            description: OK
            body:
              application/json:
                displayName: response200
                description: ''
                type: array
                items:
                  type: Item
          '401':
            description: Invalid or missing token
            body:
              application/json:
                example:
                  value:
                    message: Invalid token signature
                    status: 401
                displayName: response401
                description: ''
                type: ErrorResponse
          '404':
            description: Vault not found
            body:
              application/json:
                example:
                  value:
                    message: vault {vaultUuid} not found
                    status: 404
                displayName: response404
                description: ''
                type: ErrorResponse
      post:
        displayName: CreateVaultItem
        description: ''
        body:
          application/json:
            displayName: body
            type: FullItem
        securedBy:
        - ConnectToken
        headers:
          Content-Type:
            required: true
            displayName: Content-Type
            type: string
            enum:
            - application/json
        responses:
          '200':
            description: OK
            body:
              application/json:
                displayName: response200
                description: ''
                type: FullItem
          '400':
            description: Unable to create item due to invalid input
            body:
              application/json:
                example:
                  value:
                    message: Invalid item category
                    status: 400
                displayName: response400
                description: ''
                type: ErrorResponse
          '401':
            description: Invalid or missing token
            body:
              application/json:
                example:
                  value:
                    message: Invalid token signature
                    status: 401
                displayName: response401
                description: ''
                type: ErrorResponse
          '403':
            description: Unauthorized access
            body:
              application/json:
                example:
                  value:
                    message: vault {vaultUuid} is not in scope
                    status: 403
                displayName: response403
                description: ''
                type: ErrorResponse
          '404':
            description: Item not found
            body:
              application/json:
                examples:
                  vaultNotFound:
                    displayName: Vault not found
                    value:
                      message: vault {vaultUuid} not found
                      status: 404
                displayName: response404
                description: ''
                type: ErrorResponse
      /{itemUuid}:
        uriParameters:
          itemUuid:
            required: true
            displayName: itemUuid
            description: The UUID of the Item to update
            type: string
            pattern: ^[\da-z]{26}$
        delete:
          displayName: DeleteVaultItem
          description: ''
          securedBy:
          - ConnectToken
          responses:
            '204':
              description: Successfully deleted an item
              body: {}
            '401':
              description: Invalid or missing token
              body:
                application/json:
                  example:
                    value:
                      message: Invalid token signature
                      status: 401
                  displayName: response401
                  description: ''
                  type: ErrorResponse
            '403':
              description: Unauthorized access
              body:
                application/json:
                  example:
                    value:
                      message: vault {vaultUuid} is not in scope
                      status: 403
                  displayName: response403
                  description: ''
                  type: ErrorResponse
            '404':
              description: Item not found
              body:
                application/json:
                  examples:
                    vaultNotFound:
                      displayName: Vault not found
                      value:
                        message: vault {vaultUuid} not found
                        status: 404
                  displayName: response404
                  description: ''
                  type: ErrorResponse
        get:
          displayName: GetVaultItemById
          description: ''
          securedBy:
          - ConnectToken
          responses:
            '200':
              description: OK
              body:
                application/json:
                  displayName: response200
                  description: ''
                  type: FullItem
            '401':
              description: Invalid or missing token
              body:
                application/json:
                  example:
                    value:
                      message: Invalid token signature
                      status: 401
                  displayName: response401
                  description: ''
                  type: ErrorResponse
            '403':
              description: Unauthorized access
              body:
                application/json:
                  example:
                    value:
                      message: vault {vaultUuid} is not in scope
                      status: 403
                  displayName: response403
                  description: ''
                  type: ErrorResponse
            '404':
              description: Item not found
              body:
                application/json:
                  examples:
                    itemNotFound:
                      displayName: Item not found
                      value:
                        message: item {itemUuid} not found
                        status: 404
                    vaultNotFound:
                      displayName: Vault not found
                      value:
                        message: vault {vaultUuid} not found
                        status: 404
                  displayName: response404
                  description: ''
                  type: ErrorResponse
        patch:
          displayName: PatchVaultItem
          description: >
            Applies a modified [RFC6902 JSON Patch](https://tools.ietf.org/html/rfc6902) document to an Item or ItemField. This endpoint only supports `add`, `remove` and `replace` operations.


            When modifying a specific ItemField, the ItemField's ID in the `path` attribute of the operation object: `/fields/{fieldId}`
          body:
            application/json:
              examples:
                PatchItemField:
                  displayName: Add a new ItemField to the Item
                  value:
                  - op: add
                    path: /fields
                    value:
                      label: New Field
                      type: string
                      value: hunter2
                PatchItemFieldWithID:
                  displayName: Modify or remove an ItemField.
                  value:
                  - op: replace
                    path: /fields/r9qxq7xnhfhukoxsc8ymqr0y11
                    value:
                      label: Replacement Title
                      type: string
                      value: new value
                  - op: remove
                    path: /fields/h2nl155dshi043yse7wa3u1hs7
                ReplaceAllAttributes:
                  displayName: Replace an entire Item with new fields. Equivalent to a PUT request.
                  value:
                  - op: replace
                    path: /
                    value:
                      '...': Any attr from FullItem schema
                      favorite: true
                      tags:
                      - tag1
                      - tag2
                      title: New Title
              displayName: body
              type: array
              items:
                type: Patch
          securedBy:
          - ConnectToken
          headers:
            Content-Type:
              required: true
              displayName: Content-Type
              type: string
              enum:
              - application/json
          responses:
            '200':
              description: OK - Item updated. If no Patch operations were provided, Item is unmodified.
              body:
                application/json:
                  displayName: response200
                  description: ''
                  type: FullItem
            '401':
              description: Invalid or missing token
              body:
                application/json:
                  example:
                    value:
                      message: Invalid token signature
                      status: 401
                  displayName: response401
                  description: ''
                  type: ErrorResponse
            '403':
              description: Unauthorized access
              body:
                application/json:
                  example:
                    value:
                      message: vault {vaultUuid} is not in scope
                      status: 403
                  displayName: response403
                  description: ''
                  type: ErrorResponse
            '404':
              description: Item not found
              body:
                application/json:
                  examples:
                    itemNotFound:
                      displayName: Item not found
                      value:
                        message: item {itemUuid} not found
                        status: 404
                    vaultNotFound:
                      displayName: Vault not found
                      value:
                        message: vault {vaultUuid} not found
                        status: 404
                  displayName: response404
                  description: ''
                  type: ErrorResponse
        put:
          displayName: UpdateVaultItem
          description: ''
          body:
            application/json:
              displayName: body
              type: FullItem
          securedBy:
          - ConnectToken
          headers:
            Content-Type:
              required: true
              displayName: Content-Type
              type: string
              enum:
              - application/json
          responses:
            '200':
              description: OK
              body:
                application/json:
                  displayName: response200
                  description: ''
                  type: FullItem
            '400':
              description: Unable to create item due to invalid input
              body:
                application/json:
                  example:
                    value:
                      message: The item doesn't have a {example field name} field.
                      status: 400
                  displayName: response400
                  description: ''
                  type: ErrorResponse
            '401':
              description: Invalid or missing token
              body:
                application/json:
                  example:
                    value:
                      message: Invalid token signature
                      status: 401
                  displayName: response401
                  description: ''
                  type: ErrorResponse
            '403':
              description: Unauthorized access
              body:
                application/json:
                  example:
                    value:
                      message: vault {vaultUuid} is not in scope
                      status: 403
                  displayName: response403
                  description: ''
                  type: ErrorResponse
            '404':
              description: Item not found
              body:
                application/json:
                  examples:
                    itemNotFound:
                      displayName: Item not found
                      value:
                        message: item {itemUuid} not found
                        status: 404
                    vaultNotFound:
                      displayName: Vault not found
                      value:
                        message: vault {vaultUuid} not found
                        status: 404
                  displayName: response404
                  description: ''
                  type: ErrorResponse
        /files:
          get:
            displayName: GetItemFiles
            description: ''
            securedBy:
            - ConnectToken
            queryParameters:
              inline_files:
                required: false
                example:
                  value: true
                displayName: inline_files
                description: Tells server to return the base64-encoded file contents in the response.
                type: boolean
            responses:
              '200':
                description: OK
                body:
                  application/json:
                    displayName: response200
                    description: ''
                    type: array
                    items:
                      type: File
              '401':
                description: Invalid or missing token
                body:
                  application/json:
                    example:
                      value:
                        message: Invalid token signature
                        status: 401
                    displayName: response401
                    description: ''
                    type: ErrorResponse
              '404':
                description: Item not found
                body:
                  application/json:
                    examples:
                      itemNotFound:
                        displayName: Item not found
                        value:
                          message: item {itemUuid} not found
                          status: 404
                      vaultNotFound:
                        displayName: Vault not found
                        value:
                          message: vault {vaultUuid} not found
                          status: 404
                    displayName: response404
                    description: ''
                    type: ErrorResponse
              '413':
                description: File content too large to display
                body:
                  application/json:
                    examples:
                      fileTooLarge:
                        displayName: File too large
                        value:
                          message: File is too large to inline in request. Use the /v1/vaults/{vaultUUID}/items/{itemUUID}/files/{fileUUID}/content endpoint instead.
                          status: 413
                    displayName: response413
                    description: ''
                    type: ErrorResponse
          /{fileUuid}:
            uriParameters:
              fileUuid:
                required: true
                displayName: fileUuid
                description: The UUID of the File to fetch
                type: any
            get:
              displayName: GetDetailsOfFileById
              description: ''
              securedBy:
              - ConnectToken
              queryParameters:
                inline_files:
                  required: false
                  example:
                    value: true
                  displayName: inline_files
                  description: Tells server to return the base64-encoded file contents in the response.
                  type: boolean
              responses:
                '200':
                  description: OK
                  body:
                    application/json:
                      displayName: response200
                      description: ''
                      type: File
                '401':
                  description: Invalid or missing token
                  body:
                    application/json:
                      example:
                        value:
                          message: Invalid token signature
                          status: 401
                      displayName: response401
                      description: ''
                      type: ErrorResponse
                '403':
                  description: Unauthorized access
                  body:
                    application/json:
                      example:
                        value:
                          message: vault {vaultUuid} is not in scope
                          status: 403
                      displayName: response403
                      description: ''
                      type: ErrorResponse
                '404':
                  description: File not found
                  body:
                    application/json:
                      examples:
                        fileNotFound:
                          displayName: File not found
                          value:
                            message: file {fileUuid} not found
                            status: 404
                        itemNotFound:
                          displayName: Item not found
                          value:
                            message: item {itemUuid} not found
                            status: 404
                        vaultNotFound:
                          displayName: Vault not found
                          value:
                            message: vault {vaultUuid} not found
                            status: 404
                      displayName: response404
                      description: ''
                      type: ErrorResponse
                '413':
                  description: File content too large to display
                  body:
                    application/json:
                      examples:
                        fileTooLarge:
                          displayName: File too large
                          value:
                            message: File is too large to inline in request. Use the /v1/vaults/{vaultUUID}/items/{itemUUID}/files/{fileUUID}/content endpoint instead.
                            status: 413
                      displayName: response413
                      description: ''
                      type: ErrorResponse
            /content:
              get:
                displayName: DownloadFileByID
                description: ''
                securedBy:
                - ConnectToken
                responses:
                  '200':
                    description: Success
                    headers:
                      Content-Disposition:
                        example:
                          value: attachment; filename="privkey.pem"
                        displayName: Content-Disposition
                        type: string
                      Content-Length:
                        example:
                          value: '6432'
                        displayName: Content-Length
                        type: string
                    body:
                      application/octet-stream:
                        displayName: response200
                        description: ''
                        type: file
                  '401':
                    description: Invalid or missing token
                    body:
                      application/json:
                        example:
                          value:
                            message: Invalid token signature
                            status: 401
                        displayName: response401
                        description: ''
                        type: ErrorResponse
                  '404':
                    description: File not found
                    body:
                      application/json:
                        examples:
                          fileNotFound:
                            displayName: File not found
                            value:
                              message: file {fileUuid} not found
                              status: 404
                          itemNotFound:
                            displayName: Item not found
                            value:
                              message: item {itemUuid} not found
                              status: 404
                          vaultNotFound:
                            displayName: Vault not found
                            value:
                              message: vault {vaultUuid} not found
                              status: 404
                        displayName: response404
                        description: ''
                        type: ErrorResponse
/activity:
  get:
    displayName: GetApiActivity
    description: ''
    securedBy:
    - ConnectToken
    queryParameters:
      limit:
        required: false
        default: '50'
        example:
          value: 10
        displayName: limit
        description: How many API Events should be retrieved in a single request.
        type: integer
        format: int32
      offset:
        required: false
        default: '0'
        example:
          value: 50
        displayName: offset
        description: How far into the collection of API Events should the response start
        type: integer
        format: int32
    responses:
      '200':
        description: OK
        headers:
          Content-Range:
            example:
              value: 1-50/1134
            displayName: Content-Range
            description: An decription of what part of the collection has been returned as well as the total size.
            type: string
        body:
          application/json:
            displayName: response200
            description: ''
            type: array
            items:
              type: APIRequest
      '401':
        description: Invalid or missing token
        body:
          application/json:
            example:
              value:
                message: Invalid token signature
                status: 401
            displayName: response401
            description: ''
            type: ErrorResponse
/health:
  get:
    displayName: GetServerHealth
    description: ''
    responses:
      '200':
        description: OK
        body:
          application/json:
            examples:
              WaitingForAPIRequest:
                displayName: API server waiting for first authenticated request
                value:
                  dependencies:
                  - service: sync
                    status: TOKEN_NEEDED
                  - message: Connected to./1password.sqlite
                    service: sqlite
                    status: ACTIVE
                  name: 1Password Connect API
                  version: 1.2.1
            displayName: response200
            description: ''
            type: HealthResponse
/heartbeat:
  get:
    displayName: GetHeartbeat
    description: ''
    responses:
      '200':
        description: OK
        body:
          text/plain:
            displayName: response200
            description: ''
            type: string
/metrics:
  get:
    displayName: GetPrometheusMetrics
    description: See Prometheus documentation for a complete data model.
    responses:
      '200':
        description: Successfully returned Prometheus metrics
        body:
          text/plain:
            displayName: response200
            description: ''
            type: string
